- name: Instalar Dependências
        run: |
          pip install --upgrade pip
          pip install google-auth google-auth-oauthlib google-api-python-client requests google-genai

      - name: Executar Robô
        env:
          GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}
          GOOGLE_CLIENT_SECRET: ${{ secrets.GOOGLE_CLIENT_SECRET }}
          GOOGLE_REFRESH_TOKEN: ${{ secrets.GOOGLE_REFRESH_TOKEN }}
          AFFILIATE_TAG: ${{ secrets.AFFILIATE_TAG }}
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }} # Nova chave adicionada
        run: python main.py
